import { CharacterData, GearItem, Spell, RuleEdition } from '../types';
import { CampaignEntity } from '../utils/searchIndexer';

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  timestamp: string;
  isError?: boolean;
}

export type EntityType = 'monster' | 'npc' | 'item' | 'spell' | 'graph_node' | 'quest' | 'encounter';

const USER_API_KEY_STORAGE = 'nexus_user_ai_api_key';

export function getStoredUserApiKey(): string {
  try {
    return localStorage.getItem(USER_API_KEY_STORAGE) || localStorage.getItem('nexus_user_gemini_api_key') || '';
  } catch {
    return '';
  }
}

export function setStoredUserApiKey(key: string): void {
  try {
    if (key.trim()) {
      localStorage.setItem(USER_API_KEY_STORAGE, key.trim());
    } else {
      localStorage.removeItem(USER_API_KEY_STORAGE);
    }
  } catch {
    // ignore
  }
}

export const LANGUAGE_STORAGE_KEY = 'nexus_language_preference';

export function getStoredLanguage(): string {
  try {
    return localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en';
  } catch {
    return 'en';
  }
}

export async function askAssistant(
  message: string,
  history: Array<{ role: 'user' | 'assistant'; text: string; isError?: boolean }>,
  systemContext?: string,
  language?: string
): Promise<string> {
  const customApiKey = getStoredUserApiKey();
  const activeLang = language || getStoredLanguage();

  // Filter history to strip out error notifications
  const cleanHistory = (history || [])
    .filter((h) => !h.isError && !h.text.startsWith('⚠️ Error:') && !h.text.startsWith('⚠️ **Error:**'))
    .map((h) => ({
      role: h.role,
      text: h.text,
    }));

  let res: Response;
  try {
    res = await fetch('/api/ai/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message,
        history: cleanHistory,
        systemContext,
        customApiKey: customApiKey || undefined,
        language: activeLang,
      }),
    });
  } catch (networkErr: any) {
    throw new Error(`Network error connecting to AI service: ${networkErr.message || 'Connection failed'}`);
  }

  const rawText = await res.text();
  let data: any = {};
  try {
    data = JSON.parse(rawText);
  } catch {
    if (!res.ok) {
      throw new Error(`Server returned HTTP ${res.status} (${res.statusText || 'Service Error'}). Please retry shortly.`);
    }
    if (rawText && !rawText.trim().startsWith('<') && !rawText.trim().startsWith('<!DOCTYPE')) {
      return rawText.trim();
    }
    throw new Error('Received unexpected response format from AI service.');
  }

  if (!res.ok) {
    throw new Error(data.error || data.message || `Server error (${res.status})`);
  }

  return data.reply || 'No response was generated by the Oracle.';
}

export async function generateEntity(
  entityType: EntityType,
  prompt: string,
  edition: RuleEdition = '5e',
  context?: any,
  language?: string
): Promise<{ entity: any; entityType: EntityType }> {
  const customApiKey = getStoredUserApiKey();
  const activeLang = language || getStoredLanguage();
  let res: Response;
  try {
    res = await fetch('/api/ai/generate-entity', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        entityType,
        prompt,
        edition,
        context,
        customApiKey: customApiKey || undefined,
        language: activeLang,
      }),
    });
  } catch (networkErr: any) {
    throw new Error(`Network error connecting to AI service: ${networkErr.message || 'Connection failed'}`);
  }

  const rawText = await res.text();
  let data: any = {};
  try {
    data = JSON.parse(rawText);
  } catch {
    if (!res.ok) {
      throw new Error(`Server returned HTTP ${res.status} (${res.statusText || 'Service Error'}). Please retry shortly.`);
    }
    throw new Error('Received unexpected response format from AI generator.');
  }

  if (!res.ok) {
    throw new Error(data.error || data.message || `Failed to generate entity (${res.status})`);
  }

  return data;
}

/**
 * Hydrates raw AI monster/NPC JSON into a full, valid CharacterData object
 */
export function hydrateGeneratedMonster(raw: any, edition: RuleEdition = '5e'): CharacterData {
  const id = `ai_creature_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  const hp = Number(raw.hpMax) || 30;

  return {
    id,
    name: raw.name || 'Unnamed Creature',
    race: raw.race || 'Monstrosity',
    characterClass: raw.characterClass || 'Monster',
    subclass: raw.subclass || '',
    level: Number(raw.level) || 1,
    background: raw.background || 'Wilderness',
    alignment: raw.alignment || 'Neutral',
    experiencePoints: 0,
    edition,
    isMonster: true,
    challengeRating: String(raw.challengeRating || '1'),
    monsterXpReward: Number(raw.monsterXpReward) || 200,
    hpMax: hp,
    hpCurrent: hp,
    hpTemp: 0,
    hitDiceTotal: raw.hitDiceTotal || '4d8 + 8',
    hitDiceCurrent: 4,
    armorClass: Number(raw.armorClass) || 13,
    initiativeBonus: Number(raw.initiativeBonus) || 0,
    speed: Number(raw.speed) || 30,
    inspiration: false,
    deathSavesSuccesses: 0,
    deathSavesFailures: 0,
    abilities: {
      STR: { score: Number(raw.abilities?.STR?.score) || 14 },
      DEX: { score: Number(raw.abilities?.DEX?.score) || 12 },
      CON: { score: Number(raw.abilities?.CON?.score) || 14 },
      INT: { score: Number(raw.abilities?.INT?.score) || 10 },
      WIS: { score: Number(raw.abilities?.WIS?.score) || 12 },
      CHA: { score: Number(raw.abilities?.CHA?.score) || 10 },
    },
    savingThrowProficiencies: Array.isArray(raw.savingThrowProficiencies) ? raw.savingThrowProficiencies : [],
    skills: Array.isArray(raw.skills) ? raw.skills : [],
    classFeatures: Array.isArray(raw.classFeatures)
      ? raw.classFeatures.map((f: any, i: number) => ({
          id: f.id || `trait_${i}_${Date.now()}`,
          name: f.name || 'Special Trait',
          source: f.source || 'Monster Trait',
          description: f.description || '',
        }))
      : [],
    feats: [],
    attacks: Array.isArray(raw.attacks)
      ? raw.attacks.map((a: any, i: number) => ({
          id: a.id || `atk_${i}_${Date.now()}`,
          name: a.name || 'Strike',
          attackBonus: Number(a.attackBonus) || 4,
          damage: a.damage || '1d8 + 2',
          damageType: a.damageType || 'Slashing',
          range: a.range || 'Melee 5 ft.',
          notes: a.notes || '',
        }))
      : [],
    legendaryActions: Array.isArray(raw.legendaryActions) ? raw.legendaryActions : [],
    legendaryActionsMax: Array.isArray(raw.legendaryActions) && raw.legendaryActions.length > 0 ? 3 : 0,
    legendaryActionsRemaining: Array.isArray(raw.legendaryActions) && raw.legendaryActions.length > 0 ? 3 : 0,
    reactions: Array.isArray(raw.reactions) ? raw.reactions : [],
    wealth: { cp: 0, sp: 0, ep: 0, gp: Number(raw.wealth?.gp) || 0, pp: 0 },
    inventory: [],
    isSpellcaster: !!raw.isSpellcaster,
    spellcastingAbility: raw.spellcastingAbility || 'INT',
    spellSlots: [],
    spells: [],
    personalityTraits: '',
    ideals: '',
    bonds: '',
    flaws: '',
    backstory: raw.backstory || raw.lore || '',
    alliesAndOrganizations: '',
    additionalNotes: raw.tactics || '',
  };
}

/**
 * Hydrates raw AI item JSON into a full GearItem object
 */
export function hydrateGeneratedItem(raw: any): GearItem {
  const id = `item_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  return {
    id,
    name: raw.name || 'Mysterious Artifact',
    quantity: 1,
    weight: Number(raw.weight) || 1,
    equipped: false,
    isMagic: raw.isMagic !== false,
    attuned: !!raw.attuned,
    costGp: Number(raw.costGp) || 100,
    notes: raw.notes || raw.description || '',
    itemType: raw.itemType || 'Misc',
    armorAc: raw.armorAc ? Number(raw.armorAc) : undefined,
    armorType: raw.armorType || undefined,
    weaponStats: raw.weaponStats
      ? {
          attackBonus: raw.weaponStats.attackBonus ?? '+1',
          damage: raw.weaponStats.damage || '1d8',
          damageType: raw.weaponStats.damageType || 'Slashing',
          range: raw.weaponStats.range || 'Melee 5 ft.',
          notes: raw.weaponStats.notes || '',
        }
      : undefined,
  };
}

/**
 * Hydrates raw AI spell JSON into a full Spell object
 */
export function hydrateGeneratedSpell(raw: any, edition: RuleEdition = '5e'): Spell {
  const id = `spell_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  return {
    id,
    name: raw.name || 'Arcane Manifestation',
    level: Number(raw.level) ?? 1,
    school: raw.school || 'Evocation',
    castingTime: raw.castingTime || '1 Action',
    range: raw.range || '60 feet',
    components: raw.components || 'V, S',
    duration: raw.duration || 'Instantaneous',
    description: raw.description || '',
    shortDescription: raw.shortDescription || raw.description?.substring(0, 100) || '',
    prepared: true,
    concentration: !!raw.concentration,
    ritual: !!raw.ritual,
    saveType: raw.saveType || undefined,
    damage: raw.damage || undefined,
    damageType: raw.damageType || undefined,
    edition: edition === '3.5e' ? '3.5e' : '5e',
  };
}

/**
 * Hydrates raw AI graph node JSON into a CampaignEntity
 */
export function hydrateGeneratedGraphNode(raw: any): CampaignEntity {
  const id = `entity_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  return {
    id,
    name: raw.name || 'Unnamed Lore Entity',
    type: raw.type || 'npc',
    summary: raw.summary || raw.description || 'Campaign lore record.',
    region: raw.region || 'Realm',
    status: raw.status || 'Active',
    faction: raw.faction || '',
    tags: Array.isArray(raw.tags) ? raw.tags : [],
    connections: Array.isArray(raw.connections)
      ? raw.connections.map((c: any, i: number) => ({
          targetId: c.targetId || `rel_${i}_${Date.now()}`,
          targetName: c.targetName || 'Connected Subject',
          relationship: c.relationship || 'Associated With',
          targetType: c.targetType || 'npc',
        }))
      : [],
  };
}
