import { CharacterData, GearItem, Spell, RuleEdition, AbilityName, Skill } from '../types';
import { CampaignEntity } from '../utils/searchIndexer';
import { generateProceduralEntity } from './proceduralGenerators';

export { generateProceduralEntity };

export const DND5E_SKILL_DEFS: Array<{ name: string; ability: AbilityName }> = [
  { name: 'Acrobatics', ability: 'DEX' },
  { name: 'Animal Handling', ability: 'WIS' },
  { name: 'Arcana', ability: 'INT' },
  { name: 'Athletics', ability: 'STR' },
  { name: 'Deception', ability: 'CHA' },
  { name: 'History', ability: 'INT' },
  { name: 'Insight', ability: 'WIS' },
  { name: 'Intimidation', ability: 'CHA' },
  { name: 'Investigation', ability: 'INT' },
  { name: 'Medicine', ability: 'WIS' },
  { name: 'Nature', ability: 'INT' },
  { name: 'Perception', ability: 'WIS' },
  { name: 'Performance', ability: 'CHA' },
  { name: 'Persuasion', ability: 'CHA' },
  { name: 'Religion', ability: 'INT' },
  { name: 'Sleight of Hand', ability: 'DEX' },
  { name: 'Stealth', ability: 'DEX' },
  { name: 'Survival', ability: 'WIS' },
];

export function build5eSkillList(proficientNames: any[] = []): Skill[] {
  const profSet = new Set(
    (Array.isArray(proficientNames) ? proficientNames : [])
      .map(s => (typeof s === 'string' ? s.toLowerCase().trim() : s?.name ? String(s.name).toLowerCase().trim() : ''))
      .filter(Boolean)
  );

  return DND5E_SKILL_DEFS.map((s, idx) => ({
    id: `skill_${idx}_${s.name.toLowerCase().replace(/\s+/g, '_')}`,
    name: s.name,
    ability: s.ability,
    proficient: profSet.has(s.name.toLowerCase()),
    expertise: false,
  }));
}

export interface ChatMessageAttachment {
  data: string; // base64 string
  mimeType: string;
  previewUrl?: string;
  name?: string;
  fileSize?: number;
}

export type ChatMessageImage = ChatMessageAttachment;

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  timestamp: string;
  isError?: boolean;
  image?: ChatMessageAttachment;
  attachment?: ChatMessageAttachment;
}

export type EntityType =
  | 'character'
  | 'monster'
  | 'merchant'
  | 'npc'
  | 'item'
  | 'spell'
  | 'graph_node'
  | 'quest'
  | 'encounter'
  | 'treasure'
  | 'loot'
  | 'session_summary'
  | 'campaign_recap'
  | 'rules_adjudication'
  | 'dungeon_hazard'
  | 'tactical_room';

const USER_API_KEY_STORAGE = 'nexus_user_ai_api_key';

export function getStoredUserApiKey(): string {
  try {
    return localStorage.getItem(USER_API_KEY_STORAGE) || localStorage.getItem('nexus_user_gemini_api_key') || '';
  } catch {
    return '';
  }
}

export function setStoredUserApiKey(key: string): void {
  try {
    if (key.trim()) {
      localStorage.setItem(USER_API_KEY_STORAGE, key.trim());
    } else {
      localStorage.removeItem(USER_API_KEY_STORAGE);
    }
  } catch {
    // ignore
  }
}

export const LANGUAGE_STORAGE_KEY = 'nexus_language_preference';

export function getStoredLanguage(): string {
  try {
    return localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en';
  } catch {
    return 'en';
  }
}

export async function askAssistant(
  message: string,
  history: Array<{ role: 'user' | 'assistant'; text: string; isError?: boolean }>,
  systemContext?: string,
  language?: string,
  image?: { data: string; mimeType: string }
): Promise<string> {
  const customApiKey = getStoredUserApiKey();
  const activeLang = language || getStoredLanguage();

  // Filter history to strip out error notifications
  const cleanHistory = (history || [])
    .filter((h) => !h.isError && !h.text.startsWith('⚠️ Error:') && !h.text.startsWith('⚠️ **Error:**'))
    .map((h) => ({
      role: h.role,
      text: h.text,
    }));

  let res: Response;
  try {
    res = await fetch('/api/ai/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message,
        history: cleanHistory,
        systemContext,
        customApiKey: customApiKey || undefined,
        language: activeLang,
        image: image ? { data: image.data, mimeType: image.mimeType } : undefined,
      }),
    });
  } catch (networkErr: any) {
    throw new Error(`Network error connecting to AI service: ${networkErr.message || 'Connection failed'}`);
  }

  const rawText = await res.text();
  let data: any = {};
  try {
    data = JSON.parse(rawText);
  } catch {
    if (!res.ok) {
      throw new Error(`Server returned HTTP ${res.status} (${res.statusText || 'Service Error'}). Please retry shortly.`);
    }
    if (rawText && !rawText.trim().startsWith('<') && !rawText.trim().startsWith('<!DOCTYPE')) {
      return rawText.trim();
    }
    throw new Error('Received unexpected response format from AI service.');
  }

  if (!res.ok) {
    throw new Error(data.error || data.message || `Server error (${res.status})`);
  }

  return data.reply || 'No response was generated by the Oracle.';
}

export async function generateEntity(
  entityType: EntityType,
  prompt: string,
  edition: RuleEdition = '5e',
  context?: any,
  language?: string
): Promise<{ entity: any; entityType: EntityType; isProceduralFallback?: boolean }> {
  const customApiKey = getStoredUserApiKey();
  const activeLang = language || getStoredLanguage();

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 14000);

  try {
    const res = await fetch('/api/ai/generate-entity', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal: controller.signal,
      body: JSON.stringify({
        entityType,
        prompt,
        edition,
        context,
        customApiKey: customApiKey || undefined,
        language: activeLang,
      }),
    });
    clearTimeout(timeoutId);

    const rawText = await res.text();
    let data: any = {};
    try {
      data = JSON.parse(rawText);
    } catch {
      if (!res.ok) {
        console.warn(`[AI Engine] API returned ${res.status}, generating via procedural tables...`);
        return {
          ...generateProceduralEntity(entityType, prompt, edition, context),
          isProceduralFallback: true,
        };
      }
      throw new Error('Received unexpected response format from AI generator.');
    }

    if (!res.ok) {
      console.warn(`[AI Engine] Server responded with error (${res.status}), falling back to procedural table:`, data.error);
      return {
        ...generateProceduralEntity(entityType, prompt, edition, context),
        isProceduralFallback: true,
      };
    }

    if (!data.entity || (typeof data.entity === 'object' && Object.keys(data.entity).length === 0)) {
      return {
        ...generateProceduralEntity(entityType, prompt, edition, context),
        isProceduralFallback: true,
      };
    }

    return data;
  } catch (err: any) {
    clearTimeout(timeoutId);
    console.warn('[AI Engine] AI call failed or timed out, generating via offline procedural tables:', err?.message || err);
    return {
      ...generateProceduralEntity(entityType, prompt, edition, context),
      isProceduralFallback: true,
    };
  }
}

/**
 * Hydrates raw AI monster/NPC JSON into a full, valid CharacterData object
 */
export function hydrateGeneratedMonster(raw: any, edition: RuleEdition = '5e'): CharacterData {
  const id = `ai_creature_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  const hp = Number(raw.hpMax) || 30;

  return {
    id,
    name: raw.name || 'Unnamed Creature',
    race: raw.race || 'Monstrosity',
    characterClass: raw.characterClass || 'Monster',
    subclass: raw.subclass || '',
    level: Number(raw.level) || 1,
    background: raw.background || 'Wilderness',
    alignment: raw.alignment || 'Neutral',
    experiencePoints: 0,
    edition,
    isMonster: true,
    challengeRating: String(raw.challengeRating || '1'),
    monsterXpReward: Number(raw.monsterXpReward) || 200,
    hpMax: hp,
    hpCurrent: hp,
    hpTemp: 0,
    hitDiceTotal: raw.hitDiceTotal || '4d8 + 8',
    hitDiceCurrent: 4,
    armorClass: Number(raw.armorClass) || 13,
    initiativeBonus: Number(raw.initiativeBonus) || 0,
    speed: Number(raw.speed) || 30,
    inspiration: false,
    deathSavesSuccesses: 0,
    deathSavesFailures: 0,
    abilities: {
      STR: { score: Number(raw.abilities?.STR?.score) || 14 },
      DEX: { score: Number(raw.abilities?.DEX?.score) || 12 },
      CON: { score: Number(raw.abilities?.CON?.score) || 14 },
      INT: { score: Number(raw.abilities?.INT?.score) || 10 },
      WIS: { score: Number(raw.abilities?.WIS?.score) || 12 },
      CHA: { score: Number(raw.abilities?.CHA?.score) || 10 },
    },
    savingThrowProficiencies: Array.isArray(raw.savingThrowProficiencies) ? raw.savingThrowProficiencies : [],
    skills: build5eSkillList(raw.skills || []),
    classFeatures: Array.isArray(raw.classFeatures)
      ? raw.classFeatures.map((f: any, i: number) => ({
          id: f.id || `trait_${i}_${Date.now()}`,
          name: f.name || 'Special Trait',
          source: f.source || 'Monster Trait',
          description: f.description || '',
        }))
      : [],
    feats: [],
    attacks: Array.isArray(raw.attacks)
      ? raw.attacks.map((a: any, i: number) => ({
          id: a.id || `atk_${i}_${Date.now()}`,
          name: a.name || 'Strike',
          attackBonus: Number(a.attackBonus) || 4,
          damage: a.damage || '1d8 + 2',
          damageType: a.damageType || 'Slashing',
          range: a.range || 'Melee 5 ft.',
          notes: a.notes || '',
        }))
      : [],
    legendaryActions: Array.isArray(raw.legendaryActions) ? raw.legendaryActions : [],
    legendaryActionsMax: Array.isArray(raw.legendaryActions) && raw.legendaryActions.length > 0 ? 3 : 0,
    legendaryActionsRemaining: Array.isArray(raw.legendaryActions) && raw.legendaryActions.length > 0 ? 3 : 0,
    reactions: Array.isArray(raw.reactions) ? raw.reactions : [],
    wealth: { cp: 0, sp: 0, ep: 0, gp: Number(raw.wealth?.gp) || 0, pp: 0 },
    inventory: [],
    isSpellcaster: !!raw.isSpellcaster,
    spellcastingAbility: raw.spellcastingAbility || 'INT',
    spellSlots: [],
    spells: [],
    personalityTraits: '',
    ideals: '',
    bonds: '',
    flaws: '',
    backstory: raw.backstory || raw.lore || '',
    alliesAndOrganizations: '',
    additionalNotes: raw.tactics || '',
  };
}

/**
 * Hydrates raw AI item JSON into a full GearItem object
 */
export function hydrateGeneratedItem(raw: any): GearItem {
  const id = `item_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  return {
    id,
    name: raw.name || 'Mysterious Artifact',
    quantity: 1,
    weight: Number(raw.weight) || 1,
    equipped: false,
    isMagic: raw.isMagic !== false,
    attuned: !!raw.attuned,
    costGp: Number(raw.costGp) || 100,
    notes: raw.notes || raw.description || '',
    itemType: raw.itemType || 'Misc',
    armorAc: raw.armorAc ? Number(raw.armorAc) : undefined,
    armorType: raw.armorType || undefined,
    weaponStats: raw.weaponStats
      ? {
          attackBonus: raw.weaponStats.attackBonus ?? '+1',
          damage: raw.weaponStats.damage || '1d8',
          damageType: raw.weaponStats.damageType || 'Slashing',
          range: raw.weaponStats.range || 'Melee 5 ft.',
          notes: raw.weaponStats.notes || '',
        }
      : undefined,
  };
}

/**
 * Hydrates raw AI spell JSON into a full Spell object
 */
export function hydrateGeneratedSpell(raw: any, edition: RuleEdition = '5e'): Spell {
  const id = `spell_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  return {
    id,
    name: raw.name || 'Arcane Manifestation',
    level: Number(raw.level) ?? 1,
    school: raw.school || 'Evocation',
    castingTime: raw.castingTime || '1 Action',
    range: raw.range || '60 feet',
    components: raw.components || 'V, S',
    duration: raw.duration || 'Instantaneous',
    description: raw.description || '',
    shortDescription: raw.shortDescription || raw.description?.substring(0, 100) || '',
    prepared: true,
    concentration: !!raw.concentration,
    ritual: !!raw.ritual,
    saveType: raw.saveType || undefined,
    damage: raw.damage || undefined,
    damageType: raw.damageType || undefined,
    edition: edition === '3.5e' ? '3.5e' : '5e',
  };
}

/**
 * Hydrates raw AI character JSON into a full, valid Player Character CharacterData object
 */
export function hydrateGeneratedCharacter(raw: any, edition: RuleEdition = '5e'): CharacterData {
  const id = `pc_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  const hp = Number(raw.hpMax) || 12;

  const inv: GearItem[] = Array.isArray(raw.inventory)
    ? raw.inventory.map((item: any) => hydrateGeneratedItem(item))
    : [];

  return {
    id,
    name: raw.name || 'Unnamed Adventurer',
    race: raw.race || 'Human',
    characterClass: raw.characterClass || 'Fighter',
    subclass: raw.subclass || '',
    level: Number(raw.level) || 1,
    background: raw.background || 'Folk Hero',
    alignment: raw.alignment || 'Neutral Good',
    experiencePoints: 0,
    edition,
    isMonster: false,
    isVendor: false,
    hpMax: hp,
    hpCurrent: hp,
    hpTemp: 0,
    hitDiceTotal: raw.hitDiceTotal || '1d10 + 2',
    hitDiceCurrent: Number(raw.level) || 1,
    armorClass: Number(raw.armorClass) || 14,
    initiativeBonus: Number(raw.initiativeBonus) || 0,
    speed: Number(raw.speed) || 30,
    inspiration: false,
    deathSavesSuccesses: 0,
    deathSavesFailures: 0,
    abilities: {
      STR: { score: Number(raw.abilities?.STR?.score) || 14 },
      DEX: { score: Number(raw.abilities?.DEX?.score) || 12 },
      CON: { score: Number(raw.abilities?.CON?.score) || 14 },
      INT: { score: Number(raw.abilities?.INT?.score) || 10 },
      WIS: { score: Number(raw.abilities?.WIS?.score) || 12 },
      CHA: { score: Number(raw.abilities?.CHA?.score) || 10 },
    },
    savingThrowProficiencies: Array.isArray(raw.savingThrowProficiencies) ? raw.savingThrowProficiencies : ['STR', 'CON'],
    skills: build5eSkillList(raw.skills || ['Athletics', 'Perception']),
    classFeatures: Array.isArray(raw.classFeatures)
      ? raw.classFeatures.map((f: any, i: number) => ({
          id: f.id || `trait_${i}_${Date.now()}`,
          name: f.name || 'Class Feature',
          source: f.source || 'Class Feature',
          description: f.description || '',
        }))
      : [],
    feats: [],
    attacks: Array.isArray(raw.attacks)
      ? raw.attacks.map((a: any, i: number) => ({
          id: a.id || `atk_${i}_${Date.now()}`,
          name: a.name || 'Main Weapon',
          attackBonus: Number(a.attackBonus) || 4,
          damage: a.damage || '1d8 + 2',
          damageType: a.damageType || 'Slashing',
          range: a.range || 'Melee 5 ft.',
          notes: a.notes || '',
        }))
      : [],
    legendaryActions: [],
    legendaryActionsMax: 0,
    legendaryActionsRemaining: 0,
    reactions: [],
    wealth: {
      cp: Number(raw.wealth?.cp) || 0,
      sp: Number(raw.wealth?.sp) || 0,
      ep: Number(raw.wealth?.ep) || 0,
      gp: Number(raw.wealth?.gp) || 25,
      pp: Number(raw.wealth?.pp) || 0,
    },
    inventory: inv,
    isSpellcaster: !!raw.isSpellcaster,
    spellcastingAbility: raw.spellcastingAbility || 'INT',
    spellSlots: [],
    spells: [],
    personalityTraits: raw.personalityTraits || '',
    ideals: raw.ideals || '',
    bonds: raw.bonds || '',
    flaws: raw.flaws || '',
    backstory: raw.backstory || '',
    alliesAndOrganizations: raw.alliesAndOrganizations || '',
    additionalNotes: raw.additionalNotes || '',
  };
}

/**
 * Hydrates raw AI merchant JSON into a full CharacterData object with vendor flags & trade inventory
 */
export function hydrateGeneratedMerchant(raw: any, edition: RuleEdition = '5e'): CharacterData {
  const id = `merchant_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  const hp = Number(raw.hpMax) || 20;

  const inv: GearItem[] = Array.isArray(raw.inventory)
    ? raw.inventory.map((item: any) => hydrateGeneratedItem(item))
    : [];

  return {
    id,
    name: raw.name || 'Unnamed Merchant',
    race: raw.race || 'Human',
    characterClass: raw.characterClass || 'Merchant Shopkeeper',
    subclass: raw.subclass || raw.shopName || 'Trade Shop',
    level: Number(raw.level) || 3,
    background: raw.background || 'Guild Artisan',
    alignment: raw.alignment || 'Neutral Good',
    experiencePoints: 0,
    edition,
    isMonster: false,
    isVendor: true,
    vendorMargin: Number(raw.vendorMargin) || 100,
    hpMax: hp,
    hpCurrent: hp,
    hpTemp: 0,
    hitDiceTotal: raw.hitDiceTotal || '3d8 + 3',
    hitDiceCurrent: 3,
    armorClass: Number(raw.armorClass) || 12,
    initiativeBonus: 0,
    speed: 30,
    inspiration: false,
    deathSavesSuccesses: 0,
    deathSavesFailures: 0,
    abilities: {
      STR: { score: Number(raw.abilities?.STR?.score) || 10 },
      DEX: { score: Number(raw.abilities?.DEX?.score) || 12 },
      CON: { score: Number(raw.abilities?.CON?.score) || 12 },
      INT: { score: Number(raw.abilities?.INT?.score) || 14 },
      WIS: { score: Number(raw.abilities?.WIS?.score) || 14 },
      CHA: { score: Number(raw.abilities?.CHA?.score) || 14 },
    },
    savingThrowProficiencies: ['WIS', 'CHA'],
    skills: build5eSkillList(raw.skills || ['Insight', 'Persuasion', 'Deception']),
    classFeatures: [
      {
        id: `feat_${Date.now()}`,
        name: 'Master Appraiser',
        source: 'Merchant',
        description: 'Knows the exact market value, craftsmanship quality, and lore of rare antiquities and weapons.'
      }
    ],
    feats: [],
    attacks: [
      {
        id: `atk_${Date.now()}`,
        name: 'Dagger',
        attackBonus: 3,
        damage: '1d4 + 1',
        damageType: 'Piercing',
        range: 'Melee 5 ft. or Thrown 20/60',
        notes: 'Concealed weapon under the trade counter.'
      }
    ],
    legendaryActions: [],
    legendaryActionsMax: 0,
    legendaryActionsRemaining: 0,
    reactions: [],
    wealth: {
      cp: Number(raw.wealth?.cp) || 50,
      sp: Number(raw.wealth?.sp) || 120,
      ep: 0,
      gp: Number(raw.wealth?.gp) || 350,
      pp: Number(raw.wealth?.pp) || 2,
    },
    inventory: inv,
    isSpellcaster: false,
    spellcastingAbility: 'INT',
    spellSlots: [],
    spells: [],
    personalityTraits: raw.personalityTraits || 'Affable, sharp eye for trade, loves a fair bargain.',
    ideals: raw.ideals || 'Fair exchange and community commerce.',
    bonds: raw.bonds || raw.subclass || 'Loyal to the shop and local merchants guild.',
    flaws: raw.flaws || 'Hesitant to give discounts without a compelling story.',
    backstory: raw.backstory || raw.lore || '',
    alliesAndOrganizations: 'Merchants Guild',
    additionalNotes: `Shop: ${raw.subclass || raw.shopName || 'Trade Shop'}. Markup: ${Number(raw.vendorMargin) || 100}%`,
  };
}

/**
 * Hydrates raw AI graph/lore node JSON into a campaign graph node object
 */
export function hydrateGeneratedGraphNode(raw: any): any {
  const id = `node_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  return {
    id,
    name: raw.name || raw.title || 'Lore Entry',
    category: raw.category || raw.type || 'Location',
    summary: raw.summary || raw.description || '',
    tags: Array.isArray(raw.tags) ? raw.tags : ['lore'],
    details: raw.details || raw.notes || raw.description || '',
    connections: Array.isArray(raw.connections) ? raw.connections : [],
    timestamp: new Date().toISOString()
  };
}

export interface DetectedChatEntity {
  id: string;
  type: 'character' | 'monster' | 'merchant' | 'item' | 'spell' | 'graph_node';
  name: string;
  subtitle?: string;
  summary?: string;
  rawJson?: any;
}

/**
 * Parses assistant chat text for JSON blocks or structured statblocks that can be imported with 1-click
 */
export function extractEntitiesFromChatMessage(text: string): DetectedChatEntity[] {
  const detected: DetectedChatEntity[] = [];
  if (!text) return detected;

  const processEntityObject = (itemObj: any) => {
    if (!itemObj || typeof itemObj !== 'object') return;

    // Handle nested collections like { monsters: [...] }, { characters: [...] }, { spells: [...] }, { items: [...] }
    if (Array.isArray(itemObj.monsters)) {
      itemObj.monsters.forEach((m: any) => processEntityObject({ ...m, isMonster: true }));
      return;
    }
    if (Array.isArray(itemObj.creatures)) {
      itemObj.creatures.forEach((m: any) => processEntityObject({ ...m, isMonster: true }));
      return;
    }
    if (Array.isArray(itemObj.characters)) {
      itemObj.characters.forEach((c: any) => processEntityObject({ ...c, isMonster: false }));
      return;
    }
    if (Array.isArray(itemObj.merchants)) {
      itemObj.merchants.forEach((m: any) => processEntityObject({ ...m, isVendor: true }));
      return;
    }
    if (Array.isArray(itemObj.shops)) {
      itemObj.shops.forEach((s: any) => processEntityObject({ ...s, isVendor: true }));
      return;
    }
    if (Array.isArray(itemObj.items)) {
      itemObj.items.forEach((it: any) => processEntityObject(it));
      return;
    }
    if (Array.isArray(itemObj.spells)) {
      itemObj.spells.forEach((sp: any) => processEntityObject(sp));
      return;
    }
    if (Array.isArray(itemObj.nodes)) {
      itemObj.nodes.forEach((n: any) => processEntityObject(n));
      return;
    }
    if (Array.isArray(itemObj.entities)) {
      itemObj.entities.forEach((e: any) => processEntityObject(e));
      return;
    }

    // Check if it's a monster
    if (
      itemObj.isMonster === true ||
      itemObj.challengeRating !== undefined ||
      (itemObj.hpMax && itemObj.attacks && !itemObj.isVendor)
    ) {
      detected.push({
        id: `det_mon_${Date.now()}_${detected.length}`,
        type: 'monster',
        name: itemObj.name || 'Unnamed Creature',
        subtitle: `CR ${itemObj.challengeRating || '1'} • ${itemObj.race || 'Monster'} ${itemObj.characterClass || ''}`,
        summary: itemObj.backstory || (itemObj.hpMax ? `HP: ${itemObj.hpMax}, AC: ${itemObj.armorClass || 13}` : undefined),
        rawJson: itemObj,
      });
    }
    // Check if it's a merchant
    else if (
      itemObj.isVendor === true ||
      itemObj.vendorMargin !== undefined ||
      itemObj.shopName ||
      (itemObj.inventory && itemObj.characterClass?.toLowerCase().includes('merchant'))
    ) {
      detected.push({
        id: `det_merch_${Date.now()}_${detected.length}`,
        type: 'merchant',
        name: itemObj.name || itemObj.shopName || 'Trade Merchant',
        subtitle: `Merchant & Shop • ${itemObj.subclass || itemObj.shopName || 'General Store'}`,
        summary:
          itemObj.backstory ||
          itemObj.personalityTraits ||
          (itemObj.inventory ? `${itemObj.inventory.length} items in shop stock` : undefined),
        rawJson: itemObj,
      });
    }
    // Check if it's a player character
    else if (itemObj.isMonster === false && (itemObj.abilities || itemObj.characterClass || itemObj.background)) {
      detected.push({
        id: `det_char_${Date.now()}_${detected.length}`,
        type: 'character',
        name: itemObj.name || 'Adventurer',
        subtitle: `Level ${itemObj.level || 1} ${itemObj.race || ''} ${itemObj.characterClass || 'Hero'}`,
        summary: itemObj.backstory || (itemObj.hpMax ? `HP: ${itemObj.hpMax}, AC: ${itemObj.armorClass || 10}` : undefined),
        rawJson: itemObj,
      });
    }
    // Check if it's an item
    else if (itemObj.costGp !== undefined || itemObj.itemType || itemObj.weaponStats || itemObj.armorAc) {
      detected.push({
        id: `det_item_${Date.now()}_${detected.length}`,
        type: 'item',
        name: itemObj.name || 'Magic Item',
        subtitle: `${itemObj.itemType || 'Gear'} • ${itemObj.costGp ? `${itemObj.costGp} GP` : 'Valuable'}`,
        summary: itemObj.notes || itemObj.description,
        rawJson: itemObj,
      });
    }
    // Check if it's a spell
    else if (itemObj.school || itemObj.castingTime || itemObj.components || itemObj.level !== undefined) {
      detected.push({
        id: `det_spell_${Date.now()}_${detected.length}`,
        type: 'spell',
        name: itemObj.name || 'Arcane Spell',
        subtitle: `Level ${itemObj.level ?? 1} ${itemObj.school || 'Evocation'}`,
        summary: itemObj.description,
        rawJson: itemObj,
      });
    }
    // Check if it's a graph node
    else if (itemObj.summary && (itemObj.region || itemObj.connections || itemObj.faction)) {
      detected.push({
        id: `det_node_${Date.now()}_${detected.length}`,
        type: 'graph_node',
        name: itemObj.name || 'Campaign Lore Node',
        subtitle: `Campaign Graph • ${itemObj.type || 'Entity'}`,
        summary: itemObj.summary,
        rawJson: itemObj,
      });
    }
  };

  // 1. Look for ```json blocks
  const jsonBlockRegex = /```(?:json)?\s*([\s\S]*?)\s*```/g;
  let match: RegExpExecArray | null;

  while ((match = jsonBlockRegex.exec(text)) !== null) {
    try {
      const parsed = JSON.parse(match[1].trim());
      if (Array.isArray(parsed)) {
        parsed.forEach((item) => processEntityObject(item));
      } else if (parsed && typeof parsed === 'object') {
        processEntityObject(parsed);
      }
    } catch {
      // Not valid JSON in code block
    }
  }

  // 2. Fallback heuristic: If no JSON block found, look for structured markdown statblocks
  if (detected.length === 0) {
    // Check if monster statblock with Armor Class and Hit Points
    const nameMatch = text.match(/###?\s*(?:Monster|Creature|Boss|Statblock)?:\s*([^\n\r]+)/i) || text.match(/\*\*([A-Z][a-zA-Z\s'-]+)\*\*\s*\n\s*\*?(?:Small|Medium|Large|Huge|Gargantuan)/i);
    const crMatch = text.match(/Challenge\s*(?:Rating)?[:\s]+(\d+(?:\/\d+)?)/i) || text.match(/CR\s*[:\s]*(\d+(?:\/\d+)?)/i);
    const hpMatch = text.match(/Hit\s*Points[:\s]+(\d+)/i) || text.match(/HP[:\s]+(\d+)/i);
    const acMatch = text.match(/Armor\s*Class[:\s]+(\d+)/i) || text.match(/AC[:\s]+(\d+)/i);

    if (crMatch && hpMatch && nameMatch) {
      const monsterName = nameMatch[1].replace(/[*#]/g, '').trim();
      detected.push({
        id: `det_heur_mon_${Date.now()}`,
        type: 'monster',
        name: monsterName,
        subtitle: `CR ${crMatch[1]} • Creature`,
        summary: `HP: ${hpMatch[1]}, AC: ${acMatch ? acMatch[1] : '13'}`,
        rawJson: {
          name: monsterName,
          challengeRating: crMatch[1],
          hpMax: Number(hpMatch[1]),
          armorClass: acMatch ? Number(acMatch[1]) : 13,
          backstory: text.substring(0, 300)
        }
      });
    }
  }

  return detected;
}

export interface GeneratedEncounter {
  name: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Deadly';
  environment: string;
  description: string;
  enemies: Array<{
    name: string;
    count: number;
    cr: string;
    role: string;
    tacticalNotes: string;
    hpMax: number;
    armorClass: number;
    initiativeBonus: number;
    attacks?: Array<{
      id: string;
      name: string;
      attackBonus: number;
      damage: string;
      damageType: string;
      range: string;
      notes: string;
    }>;
    abilities?: {
      STR?: { score: number };
      DEX?: { score: number };
      CON?: { score: number };
      INT?: { score: number };
      WIS?: { score: number };
      CHA?: { score: number };
    };
  }>;
  lootAndRewards?: {
    xpTotal: number;
    goldGp: number;
    items: Array<{
      name: string;
      costGp: number;
      isMagic: boolean;
      itemType: string;
      notes: string;
    }>;
  };
  tacticsAndPhases: string;
}

export interface GeneratedTreasure {
  title: string;
  crTier: string;
  wealth: {
    cp: number;
    sp: number;
    ep: number;
    gp: number;
    pp: number;
  };
  totalGpEquivalent: number;
  gemstonesAndArt: Array<{
    name: string;
    valueGp: number;
    description: string;
  }>;
  magicItems: Array<{
    name: string;
    itemType: 'Weapon' | 'Armor' | 'Potion' | 'Scroll' | 'Wondrous Item' | 'Ring' | 'Misc';
    rarity: 'Common' | 'Uncommon' | 'Rare' | 'Very Rare' | 'Legendary';
    attunement: boolean;
    costGp: number;
    notes: string;
    weaponStats?: {
      attackBonus: number;
      damage: string;
      damageType: string;
      notes: string;
    };
    armorAc?: number;
  }>;
  loreOrigin: string;
}

export interface GeneratedSessionSummary {
  title: string;
  previouslyOn: string;
  keyEvents: Array<{
    title: string;
    description: string;
    participants: string[];
  }>;
  keyVictoriesAndCasualties: string;
  xpAndLootDistributed: {
    xpPerPlayer: number;
    goldDistributedGp: number;
    notableItems: string[];
  };
  npcRelationsChanged: Array<{
    npcName: string;
    faction: string;
    newStanding: 'Allied' | 'Friendly' | 'Neutral' | 'Suspicious' | 'Hostile';
    notes: string;
  }>;
  unresolvedHooksAndCliffhangers: string[];
  dmNotesNextSession: string;
}

export interface GeneratedRulesAdjudication {
  query: string;
  verdict: string;
  rulesAsWritten: string;
  rulesAsIntended: string;
  recommendedTableRuling: string;
  commonTrapOrMisconception: string;
}

export interface GeneratedDungeonHazard {
  roomName: string;
  sensoryDescription: string;
  dimensionsAndLighting: string;
  dynamicHazards: Array<{
    name: string;
    trigger: string;
    dcCheck: string;
    damageOrEffect: string;
    countermeasure: string;
  }>;
  tacticalFeatures: Array<{
    feature: string;
    combatBenefit: string;
  }>;
  secretOrHiddenFeature: {
    description: string;
    perceptionDc: number;
    rewardOrShortcut: string;
  };
}

export interface TacticalCombatAdvice {
  combatantName: string;
  recommendedAction: string;
  targetPriority: string;
  positioningTip: string;
  reactionWarning: string;
  moraleState: 'Fight to the death' | 'Aggressive' | 'Cautious' | 'Looking to retreat / negotiate';
}

/**
 * Phase C: Generates instant 2-3 sentence cinematic action narration for combat events
 */
export async function generateCinematicNarration(params: {
  actorName: string;
  targetName?: string;
  actionType: 'attack_hit' | 'attack_miss' | 'critical_hit' | 'spell_cast' | 'kill' | 'death_save';
  weaponOrSpell?: string;
  damageDealt?: number | string;
  damageType?: string;
  environment?: string;
}): Promise<string> {
  const customApiKey = getStoredUserApiKey();
  const lang = getStoredLanguage();

  const prompt = `You are a legendary tabletop roleplaying Game Master. Write a punchy, visceral 1 to 2 sentence cinematic narration for this combat moment:
- Actor: ${params.actorName}
- Target: ${params.targetName || 'the opponent'}
- Action: ${params.actionType}
- Weapon/Spell: ${params.weaponOrSpell || 'weapon'}
- Damage: ${params.damageDealt || ''} (${params.damageType || ''})
- Scene/Atmosphere: ${params.environment || 'the heat of battle'}

Output ONLY the dramatic narration paragraph. No introductory filler, no bullet points, no quote marks.`;

  try {
    const res = await fetch('/api/ai/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: prompt,
        history: [],
        systemContext: 'You provide brief, high-impact tabletop RPG combat narrations.',
        customApiKey: customApiKey || undefined,
        language: lang
      })
    });
    const data = await res.json();
    return data.reply?.trim() || `${params.actorName} strikes decisively with ${params.weaponOrSpell || 'their attack'}!`;
  } catch {
    return `${params.actorName} delivers a crushing strike against ${params.targetName || 'the foe'}!`;
  }
}

/**
 * Phase C: Tactical AI Turn Advice for DM / Player
 */
export async function generateTacticalCombatAdvice(params: {
  combatantName: string;
  hpPercent: number;
  availableAttacks: string[];
  legendaryActionsRemaining?: number;
  opponentsSummary: string;
  battlefieldCondition?: string;
}): Promise<TacticalCombatAdvice> {
  const customApiKey = getStoredUserApiKey();
  const lang = getStoredLanguage();

  const prompt = `Provide intelligent tactical advice for ${params.combatantName} in a 5e TRPG combat round:
- Current HP: ${params.hpPercent}%
- Attacks/Features: ${params.availableAttacks.join(', ')}
- Legendary Actions Remaining: ${params.legendaryActionsRemaining ?? 0}
- Battlefield Situation: ${params.battlefieldCondition || 'Standard arena'}
- Opponents: ${params.opponentsSummary}

Return JSON with:
{
  "combatantName": "${params.combatantName}",
  "recommendedAction": "Action, Bonus Action, and movement recommendation",
  "targetPriority": "Who to focus down and why",
  "positioningTip": "Cover, range, or engagement strategy",
  "reactionWarning": "Key trigger to save Reaction or Legendary Actions for",
  "moraleState": "Aggressive"
}`;

  try {
    const res = await fetch('/api/ai/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: prompt,
        history: [],
        systemContext: 'You are a tactical combat expert for tabletop RPGs. Always return valid raw JSON only.',
        customApiKey: customApiKey || undefined,
        language: lang
      })
    });
    const data = await res.json();
    let text = data.reply || '';
    if (text.includes('```json')) {
      text = text.split('```json')[1].split('```')[0].trim();
    } else if (text.includes('```')) {
      text = text.split('```')[1].split('```')[0].trim();
    }
    return JSON.parse(text);
  } catch {
    return {
      combatantName: params.combatantName,
      recommendedAction: `Use highest-damaging attack while maintaining tactical cover.`,
      targetPriority: `Target spellcasters or bloodied frontline enemies.`,
      positioningTip: `Stay out of flanking cones and utilize 5ft disengage steps.`,
      reactionWarning: `Reserve reaction for Opportunity Attacks or Shield / Counterspell.`,
      moraleState: params.hpPercent < 25 ? 'Looking to retreat / negotiate' : 'Aggressive'
    };
  }
}



